GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJSYWZsaSIsImVtYWlsIjoicmFmbGlAZ21haWwuY29tIiwiaWF0IjoxNjQ4OTk3Njc5LCJleHAiOjE2NDg5OTc2OTl9.PGRrZd6O5itEBA1kQ3MhxtG6drstZiXjIHzm0_uxsdA

###
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "Rafli 2",
  "email": "rafli2@gmail.com",
  "password": "qwerty",
  "confPassword": "qwertyi"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "rafli@gmail.com",
  "password": "qwerty"
}

###
GET http://localhost:5000/token